services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - DATABASE_URL=postgres://postgres:postgres@db:5432/tyvaa
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
      - redis
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tyvaa
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:latest
    volumes:
      - redisdata:/data
volumes:
  pgdata:
  redisdata:
