export default {
    testEnvironment: "node",
    testMatch: ["**/tests/**/*.test.js", "**/src/modules/**/*.test.js"],
    collectCoverage: true,
    collectCoverageFrom: [
        "src/**/*.js",
        "!**/node_modules/**",
        "!src/config/swagger.js",
        "!src/config/db.js",
        "!src/config/index.js",
        "src/utils/logger.js",
        "src/utils/mailer.js",
        "src/utils/redisCache.js",
        "!src/modules/**/models/**",
        "src/modules/**/facades/**",
        "!src/modules/**/uploads/**",
        "!src/modules/**/config/**",
        "!src/modules/**/validations/**",
        "!src/modules/**/routes/**",
        "!src/modules/**/services/**",
        "src/modules/**/cron/**",
        "!src/modules/**/server.js",
        "!src/plugins/**",
        "!**/seeder/**",
    ],
    coverageReporters: ["text", "lcov"],
    setupFiles: ["./tests/setup.js"],
    transform: {},
    moduleNameMapper: {
        "^#config/(.*)$": "<rootDir>/src/config/$1",
        "^#utils/(.*)$": "<rootDir>/src/utils/$1",
        // Add other aliases from package.json imports if needed for tests
    },
};
