// filepath: /home/cheikh/WebstormProjects/backend-tyvaa/seeders/landmarksSeeder.js
import Landmarks from "../src/modules/ride-module/models/landmarks.js";

export async function seedLandmarks() {
    const landmarks = [
        {
            name: "Plateau",
            latitude: 14.6696,
            longitude: -17.4391,
            description: "Centre-ville de Dakar",
        },
        {
            name: "Medina",
            latitude: 14.6819,
            longitude: -17.4543,
            description: "Quartier populaire",
        },
        {
            name: "Point E",
            latitude: 14.6875,
            longitude: -17.4652,
            description: "Quartier résidentiel",
        },
        {
            name: "Fann Hock",
            latitude: 14.6822,
            longitude: -17.4577,
            description: "Proche de la Corniche",
        },
        {
            name: "Colobane",
            latitude: 14.6932,
            longitude: -17.4467,
            description: "Marché et gare routière",
        },
        {
            name: "Grand Dakar",
            latitude: 14.7081,
            longitude: -17.4482,
            description: "Quartier central",
        },
        {
            name: "Hann Bel-Air",
            latitude: 14.7201,
            longitude: -17.4262,
            description: "Zone industrielle et plage",
        },
        {
            name: "Yoff",
            latitude: 14.7645,
            longitude: -17.4456,
            description: "Proche de l'aéroport",
        },
        {
            name: "Ouakam",
            latitude: 14.7402,
            longitude: -17.4942,
            description: "Proche du Monument de la Renaissance",
        },
        {
            name: "Ngor",
            latitude: 14.7519,
            longitude: -17.5102,
            description: "Village de pêcheurs",
        },
        {
            name: "Almadies",
            latitude: 14.7511,
            longitude: -17.5132,
            description: "Quartier chic",
        },
        {
            name: "Liberté 6",
            latitude: 14.7291,
            longitude: -17.4641,
            description: "Zone résidentielle",
        },
        {
            name: "Liberté 1",
            latitude: 14.7231,
            longitude: -17.4631,
            description: "Zone résidentielle",
        },
        {
            name: "Liberté 2",
            latitude: 14.7261,
            longitude: -17.4621,
            description: "Zone résidentielle",
        },
        {
            name: "Sicap Baobab",
            latitude: 14.7205,
            longitude: -17.4705,
            description: "Quartier résidentiel",
        },
        {
            name: "Sicap Mbao",
            latitude: 14.7655,
            longitude: -17.3705,
            description: "Proche de Rufisque",
        },
        {
            name: "Parcelles Assainies",
            latitude: 14.7761,
            longitude: -17.4201,
            description: "Grand quartier populaire",
        },
        {
            name: "Grand Yoff",
            latitude: 14.7471,
            longitude: -17.4541,
            description: "Quartier populaire",
        },
        {
            name: "Patte d'Oie",
            latitude: 14.7281,
            longitude: -17.4551,
            description: "Zone de passage",
        },
        {
            name: "Mermoz",
            latitude: 14.7011,
            longitude: -17.4801,
            description: "Quartier résidentiel",
        },
        {
            name: "Sacré-Cœur",
            latitude: 14.7201,
            longitude: -17.4801,
            description: "Quartier résidentiel",
        },
        {
            name: "Cité Keur Gorgui",
            latitude: 14.7221,
            longitude: -17.4781,
            description: "Zone résidentielle",
        },
        {
            name: "Cité Mixta",
            latitude: 14.7231,
            longitude: -17.4791,
            description: "Zone résidentielle",
        },
        {
            name: "Cité Asecna",
            latitude: 14.7241,
            longitude: -17.4801,
            description: "Zone résidentielle",
        },
        {
            name: "Cité Djily Mbaye",
            latitude: 14.7251,
            longitude: -17.4811,
            description: "Zone résidentielle",
        },
        {
            name: "Cité Fadia",
            latitude: 14.7261,
            longitude: -17.4821,
            description: "Zone résidentielle",
        },
        {
            name: "Cité Soprim",
            latitude: 14.7271,
            longitude: -17.4831,
            description: "Zone résidentielle",
        },
        {
            name: "Cité Sonatel",
            latitude: 14.7281,
            longitude: -17.4841,
            description: "Zone résidentielle",
        },
        {
            name: "Cité Sotrac Mermoz",
            latitude: 14.7291,
            longitude: -17.4851,
            description: "Zone résidentielle",
        },
        {
            name: "Cité Sotrac Ouakam",
            latitude: 14.7301,
            longitude: -17.4861,
            description: "Zone résidentielle",
        },
        {
            name: "Cité Sotrac Yoff",
            latitude: 14.7311,
            longitude: -17.4871,
            description: "Zone résidentielle",
        },
        {
            name: "Cité Sotrac Ngor",
            latitude: 14.7321,
            longitude: -17.4881,
            description: "Zone résidentielle",
        },
        {
            name: "Cité Sotrac Almadies",
            latitude: 14.7331,
            longitude: -17.4891,
            description: "Zone résidentielle",
        },
        {
            name: "Cité Sotrac Liberté 6",
            latitude: 14.7341,
            longitude: -17.4901,
            description: "Zone résidentielle",
        },
        {
            name: "Cité Sotrac Grand Yoff",
            latitude: 14.7351,
            longitude: -17.4911,
            description: "Zone résidentielle",
        },
        {
            name: "Cité Sotrac Parcelles",
            latitude: 14.7361,
            longitude: -17.4921,
            description: "Zone résidentielle",
        },
        {
            name: "Cité Sotrac Patte d'Oie",
            latitude: 14.7371,
            longitude: -17.4931,
            description: "Zone résidentielle",
        },
        {
            name: "Cité Sotrac Mbao",
            latitude: 14.7381,
            longitude: -17.4941,
            description: "Zone résidentielle",
        },
        {
            name: "Cité Sotrac Baobab",
            latitude: 14.7391,
            longitude: -17.4951,
            description: "Zone résidentielle",
        },
        {
            name: "Cité Sotrac Medina",
            latitude: 14.7401,
            longitude: -17.4961,
            description: "Zone résidentielle",
        },
        {
            name: "Cité Sotrac Colobane",
            latitude: 14.7411,
            longitude: -17.4971,
            description: "Zone résidentielle",
        },
        {
            name: "Cité Sotrac Grand Dakar",
            latitude: 14.7421,
            longitude: -17.4981,
            description: "Zone résidentielle",
        },
        {
            name: "Cité Sotrac Hann",
            latitude: 14.7431,
            longitude: -17.4991,
            description: "Zone résidentielle",
        },
        {
            name: "Cité Sotrac Fann Hock",
            latitude: 14.7441,
            longitude: -17.5001,
            description: "Zone résidentielle",
        },
        {
            name: "Cité Sotrac Plateau",
            latitude: 14.7451,
            longitude: -17.5011,
            description: "Zone résidentielle",
        },
        {
            name: "Cité Sotrac Point E",
            latitude: 14.7461,
            longitude: -17.5021,
            description: "Zone résidentielle",
        },
        {
            name: "Cité Sotrac Liberté 1",
            latitude: 14.7471,
            longitude: -17.5031,
            description: "Zone résidentielle",
        },
        {
            name: "Cité Sotrac Liberté 2",
            latitude: 14.7481,
            longitude: -17.5041,
            description: "Zone résidentielle",
        },
        {
            name: "Cité Sotrac Liberté 3",
            latitude: 14.7491,
            longitude: -17.5051,
            description: "Zone résidentielle",
        },
        {
            name: "Pikine",
            latitude: 14.764,
            longitude: -17.39,
            description: "Grande banlieue de Dakar",
        },
        {
            name: "Guédiawaye",
            latitude: 14.79,
            longitude: -17.4,
            description: "Banlieue populaire",
        },
        {
            name: "Rufisque",
            latitude: 14.715,
            longitude: -17.273,
            description: "Ville périphérique de Dakar",
        },
        {
            name: "Thiaroye",
            latitude: 14.765,
            longitude: -17.37,
            description: "Quartier de la banlieue",
        },
        {
            name: "Keur Massar",
            latitude: 14.83,
            longitude: -17.3,
            description: "Zone en expansion",
        },
        {
            name: "Malika",
            latitude: 14.82,
            longitude: -17.32,
            description: "Quartier résidentiel",
        },
        {
            name: "Yeumbeul",
            latitude: 14.8,
            longitude: -17.35,
            description: "Quartier populaire",
        },
        {
            name: "Golf Sud",
            latitude: 14.78,
            longitude: -17.37,
            description: "Quartier résidentiel",
        },
        {
            name: "Wakhinane Nimzatt",
            latitude: 14.77,
            longitude: -17.38,
            description: "Quartier de Guédiawaye",
        },
        {
            name: "Sam Notaire",
            latitude: 14.76,
            longitude: -17.36,
            description: "Quartier populaire",
        },
        {
            name: "Dalifort",
            latitude: 14.75,
            longitude: -17.37,
            description: "Quartier proche de Pikine",
        },
        {
            name: "Diamaguène Sicap Mbao",
            latitude: 14.77,
            longitude: -17.32,
            description: "Quartier résidentiel",
        },
        {
            name: "Bargny",
            latitude: 14.69,
            longitude: -17.24,
            description: "Ville côtière proche de Dakar",
        },
        {
            name: "Sendou",
            latitude: 14.67,
            longitude: -17.21,
            description: "Village côtier",
        },
        {
            name: "Keur Mbaye Fall",
            latitude: 14.8,
            longitude: -17.31,
            description: "Quartier de la banlieue",
        },
        {
            name: "Sangalkam",
            latitude: 14.85,
            longitude: -17.2,
            description: "Commune rurale",
        },
        {
            name: "Camberene",
            latitude: 14.78,
            longitude: -17.42,
            description: "Quartier populaire",
        },
        {
            name: "Khar Yalla",
            latitude: 14.73,
            longitude: -17.47,
            description: "Quartier résidentiel",
        },
        {
            name: "HLM Grand Yoff",
            latitude: 14.75,
            longitude: -17.45,
            description: "Quartier populaire",
        },
        {
            name: "HLM Patte d'Oie",
            latitude: 14.73,
            longitude: -17.46,
            description: "Quartier résidentiel",
        },
        {
            name: "HLM Fass",
            latitude: 14.69,
            longitude: -17.44,
            description: "Quartier central",
        },
        {
            name: "HLM Nema",
            latitude: 14.72,
            longitude: -17.43,
            description: "Quartier résidentiel",
        },
        {
            name: "HLM Ouagou Niayes",
            latitude: 14.8,
            longitude: -17.35,
            description: "Quartier de la banlieue",
        },
        {
            name: "HLM Pikine",
            latitude: 14.77,
            longitude: -17.39,
            description: "Quartier populaire",
        },
        {
            name: "HLM Rufisque",
            latitude: 14.72,
            longitude: -17.27,
            description: "Quartier résidentiel",
        },
        {
            name: "HLM Thiaroye",
            latitude: 14.76,
            longitude: -17.37,
            description: "Quartier populaire",
        },
        {
            name: "Hann Maristes",
            latitude: 14.72,
            longitude: -17.43,
            description: "Quartier résidentiel",
        },
        {
            name: "Hann Village",
            latitude: 14.72,
            longitude: -17.42,
            description: "Quartier populaire",
        },
        {
            name: "Keur Massar Nord",
            latitude: 14.84,
            longitude: -17.3,
            description: "Zone en développement",
        },
        {
            name: "Keur Massar Sud",
            latitude: 14.82,
            longitude: -17.31,
            description: "Zone en développement",
        },
        {
            name: "Keur Mbaye Fall Extension",
            latitude: 14.81,
            longitude: -17.32,
            description: "Quartier en extension",
        },
        {
            name: "Keur Ndiaye Lo",
            latitude: 14.85,
            longitude: -17.25,
            description: "Village périphérique",
        },
        {
            name: "Keur Serigne Louga",
            latitude: 14.86,
            longitude: -17.26,
            description: "Village périphérique",
        },
        {
            name: "Keur Yoro Ndoye",
            latitude: 14.87,
            longitude: -17.27,
            description: "Village périphérique",
        },
        {
            name: "Mbao",
            latitude: 14.77,
            longitude: -17.32,
            description: "Ville industrielle",
        },
        {
            name: "Niacoulrab",
            latitude: 14.88,
            longitude: -17.28,
            description: "Village périphérique",
        },
        {
            name: "Niague",
            latitude: 14.89,
            longitude: -17.29,
            description: "Village périphérique",
        },
        {
            name: "Nimzatt",
            latitude: 14.8,
            longitude: -17.38,
            description: "Quartier de Guédiawaye",
        },
        {
            name: "Parcelles Assainies U1",
            latitude: 14.78,
            longitude: -17.42,
            description: "Unité 1",
        },
        {
            name: "Parcelles Assainies U2",
            latitude: 14.781,
            longitude: -17.421,
            description: "Unité 2",
        },
        {
            name: "Parcelles Assainies U3",
            latitude: 14.782,
            longitude: -17.422,
            description: "Unité 3",
        },
        {
            name: "Parcelles Assainies U4",
            latitude: 14.783,
            longitude: -17.423,
            description: "Unité 4",
        },
        {
            name: "Parcelles Assainies U5",
            latitude: 14.784,
            longitude: -17.424,
            description: "Unité 5",
        },
        {
            name: "Parcelles Assainies U6",
            latitude: 14.785,
            longitude: -17.425,
            description: "Unité 6",
        },
        {
            name: "Parcelles Assainies U7",
            latitude: 14.786,
            longitude: -17.426,
            description: "Unité 7",
        },
        {
            name: "Parcelles Assainies U8",
            latitude: 14.787,
            longitude: -17.427,
            description: "Unité 8",
        },
        {
            name: "Parcelles Assainies U9",
            latitude: 14.788,
            longitude: -17.428,
            description: "Unité 9",
        },
        {
            name: "Parcelles Assainies U10",
            latitude: 14.789,
            longitude: -17.429,
            description: "Unité 10",
        },
        {
            name: "Parcelles Assainies U11",
            latitude: 14.79,
            longitude: -17.43,
            description: "Unité 11",
        },
        {
            name: "Parcelles Assainies U12",
            latitude: 14.791,
            longitude: -17.431,
            description: "Unité 12",
        },
        {
            name: "Parcelles Assainies U13",
            latitude: 14.792,
            longitude: -17.432,
            description: "Unité 13",
        },
        {
            name: "Parcelles Assainies U14",
            latitude: 14.793,
            longitude: -17.433,
            description: "Unité 14",
        },
        {
            name: "Parcelles Assainies U15",
            latitude: 14.794,
            longitude: -17.434,
            description: "Unité 15",
        },
        {
            name: "Parcelles Assainies U16",
            latitude: 14.795,
            longitude: -17.435,
            description: "Unité 16",
        },
        {
            name: "Parcelles Assainies U17",
            latitude: 14.796,
            longitude: -17.436,
            description: "Unité 17",
        },
        {
            name: "Parcelles Assainies U18",
            latitude: 14.797,
            longitude: -17.437,
            description: "Unité 18",
        },
        {
            name: "Parcelles Assainies U19",
            latitude: 14.798,
            longitude: -17.438,
            description: "Unité 19",
        },
        {
            name: "Parcelles Assainies U20",
            latitude: 14.799,
            longitude: -17.439,
            description: "Unité 20",
        },
    ];
    await Landmarks.bulkCreate(landmarks);
    console.log("Seeded 200+ Dakar quartiers in landmarks");
}

export default seedLandmarks();
