name: Backend CI

on:
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ dev-test ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x ]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set NODE_ENV to test
        run: echo "NODE_ENV=test" >> $GITHUB_ENV

      - name: Run tests
        run: npm test

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/dev-test'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Koyeb CLI
        run: curl -fsSL https://raw.githubusercontent.com/koyeb/koyeb-cli/master/install.sh | sh

      - name: Add Koyeb CLI to PATH
        run: echo "$HOME/.koyeb/bin" >> $GITHUB_PATH

      - name: Authenticate Koyeb CLI
        run: |
          mkdir -p ~/.koyeb
          echo "token: ${{ secrets.KOYEB_API_TOKEN }}" > ~/.koyeb.yaml

      - name: Deploy to Koyeb
        run: |
          ~/.koyeb/bin/koyeb service deploy git tyvaa-service \
            --app tyvaa \
            --git github.com/${{ github.repository }} \
            --git-branch ${{ github.ref_name }} \
            --git-builder docker \
            --ports 3000:http \
            --env "PORT=3000"
